      
      
        let identify = document.getElementById("identify")
        let imageContainer = document.getElementById("image-container");
        let image = document.getElementById("image");
        let start = document.getElementById("start");
        let resultElement = document.getElementById("result");
        let list = document.getElementById('list')
        let elephant = document.getElementById('ele')
        let cat = document.getElementById('cat')
        let dog = document.getElementById('dog')
        let car = document.getElementById('car')
        let banana = document.getElementById('banana')


        
      
         
    
        

        function changeImage(){

            image.src = "images/cat.jpg"

             document.getElementById("identify").innerHTML= "Identify the Object Below"


        }




        let objectsToIdentify = ("cat", "dog", "elephant", "banana")
        <img src="images/cat.jpg" alt="Cat" class="image">,
         <img src="images/dog.jpg" alt="Dog" class="image">,
         <img src="images/ele.jpg" alt="Elephant" class="image">,
         <img src="images/banana.jpg" alt="Banana" class="image">,





         function changeImage(){

let img = document.createElement('img');
img.src = "images/cat.jpg";
img.alt = 'Alternative text for the image';
document.body.appendChild(img);
img.style.height= '390px'
img.style.width= '440px'


document.getElementById("identify").innerHTML= "Identify the Object Below";
}
















let number = Math.floor(Math.random() * 11);

console.log(number)


// declare an array to store the images

let ImageArray = new Array();

// insert the URL of images in array

function getRandomImage(){

randomImage[0] = images/cat.jpg

randomImage[1] = images/dog.jpg

randomImage[2] = images/elephant.jpg

randomImage[3] = images/banana.jpg

randomImage[4] = images/car.jpg

randomImage[5] = images/fox.jpg

randomImage[6] = images/butterfly.jpg

randomImage[7] = images/lizard.jpg

randomImage[8] = images/bear.jpg

randomImage[9] = images/lion.jpg





// generate a number and provide to the image to generate randomly

let number = Math.floor(Math.random() * 11);

let img = ImageArray[num]



// return the images generated by a random number

document.getElementById("result").innerHTML = ('<img src="' + 'images/random/' + img + '" width="690px">')

  



}  

